title: BiomedFacts
description: Evidence-based health & biomedical science publication

url: "https://biomedfacts.com"
baseurl: ""

timezone: Europe/Athens

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
